includes:
- configs/s2ef/200k/base.yml

model:
  name: cgcnn
  atom_embedding_size: 128
  fc_feat_size: 128
  num_fc_layers: 3
  num_graph_conv_layers: 2
  cutoff: 6.0
  num_gaussians: 100
  use_pbc: True

# *** Important note ***
#   The total number of gpus used for this run was 4.
#   If the global batch size (num_gpus * batch_size) is modified
#   the lr_milestones and warmup_steps need to be adjusted accordingly.

optim:
  batch_size: {batch_size}
  eval_batch_size: {batch_size}
  num_workers: {loader_workers}
  lr_initial: 0.0005
  lr_gamma: 0.1
  lr_milestones: # steps at which lr_initial <- lr_initial * lr_gamma
    - 23437
    - 31250
  warmup_steps: 3125
  warmup_factor: 0.2
  max_epochs: 1
  force_coefficient: 10
